system:
  version: "1.0.0-test"
  name: "AI Code Assistant Test"
  session_timeout: "1h"
  auto_save_config: true
  data_directory: "./test-data"

ai:
  providers:
    - name: "openai"
      model: "gpt-4"
      weight: 1.0
      timeout: "30s"
      max_tokens: 4096
      temperature: 0.7
      stream: true
      enabled: true
      cost_per_1k_input: 0.03
      cost_per_1k_output: 0.06

indexing:
  languages: ["go", "python", "javascript"]
  file_extensions: [".go", ".py", ".js", ".ts"]
  ignore_patterns: ["vendor/", "node_modules/", ".git/"]
  chunk_size: 1000
  overlap: 100
  batch_size: 50
  max_workers: 4

search:
  max_results: 20
  min_confidence: 0.5
  semantic_weight: 0.6
  keyword_weight: 0.2
  graph_weight: 0.2
